### ISSUE TITLE
Incorrect comorbidity calculation for some non-existent codes

### ISSUE THREAD

**Issue by jackwasey** [patrickmdnet/medicalrisk#3]
Hi Patrick, hope you're well.

I took some time to compare the results of the 'icd' packge and yours for Quan Deyo Charlson comorbidities. I'm glad there are several implementations of comorbidity calculations out there to do this kind of cross-validation.

I discovered, using some randomly generated data with many non-existent codes, that 'medicalrisk' perhaps incorrectly assigns chronic lung disease to ICD-9 code 498.87

This code doesn't exist, and in fact, not even the 498 top-level exists, although it is nearby a family of pulmonary codes (up to 496).

My approach with 'icd' was to be tolerant of incorrect additions, e.g. 496.7 isn't in ICD-9-CM any year, but I would count this because it falls under 496. If coders are getting the three-digit code wrong, I thought all bets were off! What do you think?

In addition, I've yet to investigate wider discrepancies between the 'comorbidity' package and each of ours, particularly in the broad 'cancer' category.
Jack

**Comment by patrickmdnet** [comment]
Yes, `medicalrisk` makes the assumption that the input does not contain codes that are invalid or otherwise unknown to the people who developed the mappings.  Probably not a great thing.

I agree that unknown three-digit roots should not be mapped to anything.

The reason 498* is mapped to chrnlung is that `medicalrisk` uses these regular expressions:

[icd9cm.R#L167](https://github.com/patrickmdnet/medicalrisk/blob/ac24ac91c39c919f49f93481ebedf9b6fe180f57/R/icd9cm.R#L167) and [icd9cm.R#L232](https://github.com/patrickmdnet/medicalrisk/blob/ac24ac91c39c919f49f93481ebedf9b6fe180f57/R/icd9cm.R#L232):
```r
chrnlung = grepl('^D(416[89]|49|50[0-5]|5064|508[18])', icd9),
```

[icd9cm.R#L330](https://github.com/patrickmdnet/medicalrisk/blob/ac24ac91c39c919f49f93481ebedf9b6fe180f57/R/icd9cm.R#L330):
```r
chrnlung = grepl('^D(49|50[0-5]|5064)', icd9),
```

Fixing this would either require A) determining which ICD codes are valid, or B) changing the regular expression to ignore unknown ICD roots.

As you can tell by the huge latency with my response I haven't been using `medicalrisk` myself as much as I once did, and I don't think others are either, so I'm going to mark this as wontfix.
